[package]
name = "anime4k"
version = "0.1.0"
authors = ["Andra Antariksa Prihadi <andra.antariksa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.10"
clap = "4.6.6"
raster = { git = "https://github.com/kosinix/raster.git", rev = "f54e52004ef889748caf2322d5bd9e25837615ef" }